name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Koyeb
        uses: koyeb/action@v1
        with:
          token: ${{ secrets.ui9f19nk3vuy5pizopp8knrt8vcihdn88ak2pxdhco1zpwtih2i39wz29gefram7 }}
          file: ./index.js
